# Generated by Django 6.0 on 2025-12-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='entity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
